config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search"=>"searches#search", as: "search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update, :follow_users] do
    member do
      get :follow_users, :follower_users
    end
    resource :relationship, only: [:create, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    # book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_back fallback_location: root_path
  end

  def destroy
    @book = Book.find(params[:book_id])
    # book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_back fallback_location: root_path
  end

end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true, data: {"turbolinks" => false}, class:"text-danger" do %>
      ♥<%= book.favorites.count %>
    <% end %>
  </p>
  <% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true, data: {"turbolinks" => false} do %>
      ♡<%= book.favorites.count %>
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$('#index_favorite_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");
$('#show_favorite_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#index_favorite_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");
$('#show_favorite_<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");