config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "search"=>"searches#search", as: "search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update, :follow_users] do
    member do
      get :follow_users, :follower_users
    end
    resource :relationship, only: [:create, :destroy]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
# frozen_string_literal: true

class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence:true
end

app/controllers/book_comments_controller.rb
# frozen_string_literal: true

class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    # book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.book_id = @book.id
    comment.user_id = current_user.id
    comment.save
    # redirect_to book_path(book)
  end

  def destroy
    @book = Book.find(params[:book_id])
    BookComment.find(params[:id]).destroy
    # redirect_to book_path(params[:book_id])
  end

  private
    def book_comment_params
      params.require(:book_comment).permit(:comment)
    end

end

app/helpers/book_comments_helper.rb
# frozen_string_literal: true

module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <div class="d-flex align-items-center">
    <div class="mr-2">
      <%= link_to(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
        <%= book_comment.user.name %>
      <% end %>
    </div>
    <div class="mx-2">
      <%= book_comment.comment %>
    </div>
    <% if book_comment.user == current_user %>
      <div class="mx-2">
        <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-sm btn-danger", remote:true, data: {"turbolinks" => false} %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, book_comment], local: false do |f| %>
  <div class="form-group">
  <%= f.text_area :comment, rows: '5', class: "form-control", placeholder: "コメントをここに" %>
  </div>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
$('#book-comments').html("<%= j(render "book_comments/comments", book: @book) %>");
$('#comment_count').html("<%= @book.book_comments.count %>");
$("textarea").val('');

app/views/book_comments/destroy.js.erb
$('#book-comments').html("<%= j(render "book_comments/comments", book: @book) %>");
$('#comment_count').html("<%= @book.book_comments.count %>");